
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Moderate", targetNamespace = "http://moderate_advertisement/", wsdlLocation = "http://localhost:8082/ModerateAdvertisement?wsdl")
public class Moderate
    extends Service
{

    private final static URL MODERATE_WSDL_LOCATION;
    private final static WebServiceException MODERATE_EXCEPTION;
    private final static QName MODERATE_QNAME = new QName("http://moderate_advertisement/", "Moderate");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/ModerateAdvertisement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODERATE_WSDL_LOCATION = url;
        MODERATE_EXCEPTION = e;
    }

    public Moderate() {
        super(__getWsdlLocation(), MODERATE_QNAME);
    }

    public Moderate(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODERATE_QNAME, features);
    }

    public Moderate(URL wsdlLocation) {
        super(wsdlLocation, MODERATE_QNAME);
    }

    public Moderate(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODERATE_QNAME, features);
    }

    public Moderate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Moderate(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModerateAdvertisementService
     */
    @WebEndpoint(name = "ModeratePort")
    public ModerateAdvertisementService getModeratePort() {
        return super.getPort(new QName("http://moderate_advertisement/", "ModeratePort"), ModerateAdvertisementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModerateAdvertisementService
     */
    @WebEndpoint(name = "ModeratePort")
    public ModerateAdvertisementService getModeratePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://moderate_advertisement/", "ModeratePort"), ModerateAdvertisementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODERATE_EXCEPTION!= null) {
            throw MODERATE_EXCEPTION;
        }
        return MODERATE_WSDL_LOCATION;
    }

}
