
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PostAdvertisementService", targetNamespace = "http://post_advertisement/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PostAdvertisementService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client.PostAdvertisementStatement
     */
    @WebMethod(operationName = "CreateStatement")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateStatement", targetNamespace = "http://post_advertisement/", className = "client.CreateStatement")
    @ResponseWrapper(localName = "CreateStatementResponse", targetNamespace = "http://post_advertisement/", className = "client.CreateStatementResponse")
    @Action(input = "http://post_advertisement/PostAdvertisementService/CreateStatementRequest", output = "http://post_advertisement/PostAdvertisementService/CreateStatementResponse")
    public PostAdvertisementStatement createStatement(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns client.PostAdvertisementStatement
     */
    @WebMethod(operationName = "EditDescription")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "EditDescription", targetNamespace = "http://post_advertisement/", className = "client.EditDescription")
    @ResponseWrapper(localName = "EditDescriptionResponse", targetNamespace = "http://post_advertisement/", className = "client.EditDescriptionResponse")
    @Action(input = "http://post_advertisement/PostAdvertisementService/EditDescriptionRequest", output = "http://post_advertisement/PostAdvertisementService/EditDescriptionResponse")
    public PostAdvertisementStatement editDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        PostAdvertisementStatement arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns client.PostAdvertisementStatement
     */
    @WebMethod(operationName = "SubmitForReview")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SubmitForReview", targetNamespace = "http://post_advertisement/", className = "client.SubmitForReview")
    @ResponseWrapper(localName = "SubmitForReviewResponse", targetNamespace = "http://post_advertisement/", className = "client.SubmitForReviewResponse")
    @Action(input = "http://post_advertisement/PostAdvertisementService/SubmitForReviewRequest", output = "http://post_advertisement/PostAdvertisementService/SubmitForReviewResponse")
    public PostAdvertisementStatement submitForReview(
        @WebParam(name = "arg0", targetNamespace = "")
        PostAdvertisementStatement arg0);

}
