
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostAdvertisement", targetNamespace = "http://post_advertisement/", wsdlLocation = "http://localhost:8081/PostAdvertisement?wsdl")
public class PostAdvertisement
    extends Service
{

    private final static URL POSTADVERTISEMENT_WSDL_LOCATION;
    private final static WebServiceException POSTADVERTISEMENT_EXCEPTION;
    private final static QName POSTADVERTISEMENT_QNAME = new QName("http://post_advertisement/", "PostAdvertisement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/PostAdvertisement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTADVERTISEMENT_WSDL_LOCATION = url;
        POSTADVERTISEMENT_EXCEPTION = e;
    }

    public PostAdvertisement() {
        super(__getWsdlLocation(), POSTADVERTISEMENT_QNAME);
    }

    public PostAdvertisement(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTADVERTISEMENT_QNAME, features);
    }

    public PostAdvertisement(URL wsdlLocation) {
        super(wsdlLocation, POSTADVERTISEMENT_QNAME);
    }

    public PostAdvertisement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTADVERTISEMENT_QNAME, features);
    }

    public PostAdvertisement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostAdvertisement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostAdvertisementService
     */
    @WebEndpoint(name = "PostAdvertisementPort")
    public PostAdvertisementService getPostAdvertisementPort() {
        return super.getPort(new QName("http://post_advertisement/", "PostAdvertisementPort"), PostAdvertisementService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostAdvertisementService
     */
    @WebEndpoint(name = "PostAdvertisementPort")
    public PostAdvertisementService getPostAdvertisementPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://post_advertisement/", "PostAdvertisementPort"), PostAdvertisementService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTADVERTISEMENT_EXCEPTION!= null) {
            throw POSTADVERTISEMENT_EXCEPTION;
        }
        return POSTADVERTISEMENT_WSDL_LOCATION;
    }

}
